spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:product;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
