spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa

  jpa:
    database: h2
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
