drop table if exists member CASCADE;
drop table if exists order_detail CASCADE;

create table member
(
    id    bigint generated by default as identity,
    money integer not null,
    primary key (id)
);

create table order_detail
(
    id            bigint generated by default as identity,
    product_name  varchar(255) not null,
    product_price integer      not null,
    customer_id   bigint       not null,
    owner_id      bigint       not null,
    primary key (id)
);

alter table order_detail
    add constraint FK30tg6hosx2u0852u9wo8ocmfg
        foreign key (customer_id)
            references member;

alter table order_detail
    add constraint FKokxrof4wf328mj2p02odclhh9
        foreign key (owner_id)
            references member;
