spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:baseCode;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
